@startuml

Person : username
Person : age

' Method 
Person : getUsername()
Person : getAge()

TelePhoneNumber : phoneNumber
TelePhoneNumber : getPhoneNumber()

NewPerson : username
NewPerson : age
NewPerson : phoneNumber
NewPerson : getUsername()
NewPerson : getAge()
NewPerson : getPhoneNumber()

' Relation
Person - TelePhoneNumber
TelePhoneNumber - NewPerson : 合并 > 

@enduml